workflows:
  ios-simulator:
    name: iOS Simulator Build
    instance_type: mac_mini_m2
    max_build_duration: 30
    environment:
      node: latest
      xcode: latest
      vars:
        PROJECT_NAME: "MovieApp"
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Install CocoaPods
        script: |
          cd ios
          pod install
      - name: Bundle React Native code and assets
        script: |
          mkdir -p ios/build
          npx react-native bundle \
            --entry-file index.js \
            --platform ios \
            --dev false \
            --bundle-output ios/build/main.jsbundle \
            --assets-dest ios/build
      - name: Copy JS bundle into Xcode project
        script: |
          cp ios/build/main.jsbundle ios/
      - name: Build iOS simulator app
        script: |
          cd ios
          xcodebuild \
            -workspace "${PROJECT_NAME}.xcworkspace" \
            -scheme "${PROJECT_NAME}" \
            -sdk iphonesimulator \
            -configuration Debug \
            -derivedDataPath build \
            -UseModernBuildSystem=YES
    artifacts:
      - ios/build/Build/Products/Debug-iphonesimulator/*.app
