workflows:
  ios-simulator:
    name: iOS Simulator Build
    instance_type: mac_mini_m2
    max_build_duration: 30
    environment:
      node: latest
      xcode: latest
      vars:
        PROJECT_NAME: "MovieApp"
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Install CocoaPods
        script: |
          cd ios
          pod install
      - name: Bundle JavaScript for iOS
        script: |
          npx react-native bundle \
            --platform ios \
            --dev false \
            --entry-file index.js \
            --bundle-output ios/main.jsbundle \
            --assets-dest ios
      - name: Build for iOS Simulator
        script: |
          cd ios
          xcodebuild \
            -workspace "${PROJECT_NAME}.xcworkspace" \
            -scheme "${PROJECT_NAME}" \
            -sdk iphonesimulator \
            -configuration Debug \
            -derivedDataPath build
    artifacts:
      - ios/build/Build/Products/Debug-iphonesimulator/*.app
